version: 2
jobs:
  release:
    working_directory: /go/src/github.com/utdal/openroadm_exporter
    docker:
      # Whenever the Go version is updated here, .promu.yml should also be updated.
      - image: circleci/golang:1.13
    steps:
      - checkout
      - setup_remote_docker
      - run: make setup_promu
      - run: ./promu crossbuild
      - run: ./promu crossbuild tarballs
      - run: ./promu checksum .tarballs
      - run: ./promu release .tarballs
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
